@api = http://localhost:3000/gatepass/v2/admin


###Dashboard

###Getting pending_requests_count
GET {{api}}/pending_request

###Getting student_in_campus count
GET {{api}}/student_in_campus

###Getting student_out_campus count
GET {{api}}/student_out_campus

###Getting blacklist_student count
GET {{api}}/blacklist_student

###Getting profile_request count
GET {{api}}/profile_request

###Getting today_gatepass table
GET {{api}}/today_gatepass

###Getting all_pending_request table
GET {{api}}/all_pending_request


###Settings

###Getting groups
GET {{api}}/group

###Getting subgroups
GET {{api}}/subgroup

###Getting roles
GET {{api}}/all_role

###Getting User Roles
GET {{api}}/user_role

###Getting roles
GET {{api}}/all_status

###Getting parameter_config
GET {{api}}/parameter_config